from .prompt_deck import NODE_CLASS_MAPPINGS as _DECK_NODES, NODE_DISPLAY_NAME_MAPPINGS as _DECK_NAMES
from .keeper import NODE_CLASS_MAPPINGS as _KEEPER_NODES, NODE_DISPLAY_NAME_MAPPINGS as _KEEPER_NAMES

NODE_CLASS_MAPPINGS = {**_DECK_NODES, **_KEEPER_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**_DECK_NAMES, **_KEEPER_NAMES}

WEB_DIRECTORY = "./web/js"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
